server:
  port: 8081
  servlet:
      context-path: /zq_box
spring:
  pid:
    file: c:/service/box/application.pid
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      
  profiles:
    active: 
    - file
    
  datasource:
    url: jdbc:mysql://192.168.0.108:3306/zq_box?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.0.108
    port: 6379
    password: ILoveChina
    timeout: PT30S
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:zq/bim/mapper/*.xml
  type-aliases-package: zq.bim.entity
  ##开启驼峰映射实体
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    zq:
      bim:
        dao: DEBUG
